name: Prova GitHub Actions Schedule
run-name: ${{ github.actor }} fa una prova schedule
on:
  schedule:
    - cron: '43 * * * *'
jobs:
  Prova-Github-Actions-Schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Comprova el codi del repositori
        uses: actions/checkout@v5
      - name: Modificar fitxer.txt
        run: |
          echo "Programat "`date` >> fitxer.txt
      - name: commit i push
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add --all
          git commit -m "Afegit contingut a fitxer.txt"
          git push
